# Generated by Django 5.1.2 on 2024-10-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Internal Medicine', 'Internal Medicine'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology'), ('Surgery', 'Surgery'), ('Laboratory', 'Laboratory'), ('Neonatology', 'Neonatology')], max_length=50)),
                ('experience_years', models.PositiveIntegerField()),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
